var returnGroupTeams= {
  "GroupTeams": 
     {
       "GroupID":23,
       "EventID":12,
       "Teams":
	 [
	  {
	    "TeamID":333,
		"EntrantID":7,
		"EntrantFName":"Mark",
		"EntrantLName":"Holton",
		"TotalGrossRelPar":35,
		"TotalNetRelPar":47,
		"Golfers":[123, 32, 24, 49, 97, 165]
	  },
	  {
	    	"TeamID":1373,
		"EntrantID":437,
		"EntrantFName":"Mona",
		"EntrantLName":"Aflatooni",
		"TotalGrossRelPar":35,
		"TotalNetRelPar":47,
		"Golfers":[123, 32, 24, 49, 97, 165]
	  },
	  {
	    	"TeamID":2343,
		"EntrantID":89,
		"EntrantFName":"Wally",
		"EntrantLName":"Holton",
		"TotalGrossRelPar":35,
		"TotalNetRelPar":47,
		"Golfers":[123, 32, 24, 49, 97, 165]
	  },
	  {
	    	"TeamID":3333,
		"EntrantID":2213,
		"EntrantFName":"Mr",
		"EntrantLName":"Eye",
		"TotalGrossRelPar":35,
		"TotalNetRelPar":47,
		"Golfers":[123, 32, 24, 49, 97, 165]
	  }

	 ]		
	}
};

var active_golfers = {
  "Golfers":
     [
	{
	  "GolferID":123,
	  "GolferFName":"Greg",
	  "GolferLName":"Norman",
	  "CurrentScoreRelPar":-4,
	  "EoMHandicap":3,
	  "CurrentNetScore":-1,
	  "img_name":"normangreg.gif"
	},
	{
	  "GolferID":32,
	  "GolferFName":"Nick",
	  "GolferLName":"Faldo",
	  "CurrentScoreRelPar":-6,
	  "EoMHandicap":2,
	  "CurrentNetScore":-4,
	  "img_name":"faldonick.gif"
	},
	{
	  "GolferID":24,
	  "GolferFName":"Curtis",
	  "GolferLName":"Strange",
	  "CurrentScoreRelPar":-8,
	  "EoMHandicap":0,
	  "CurrentNetScore":-8,
	  "img_name":"strangecurtis.gif"
	},
	{
	  "GolferID":49,
	  "GolferFName":"Mike",
	  "GolferLName":"Kovaleski",
	  "CurrentScoreRelPar":-8,
	  "EoMHandicap":0,
	  "CurrentNetScore":-8,
	  "img_name":"kovaleski.gif"
	},
	{
	  "GolferID":97,
	  "GolferFName":"Chris",
	  "GolferLName":"Zorich",
	  "CurrentScoreRelPar":-8,
	  "EoMHandicap":0,
	  "CurrentNetScore":-8,
	  "img_name":"chriszorich.gif"
	},
	{
	  "GolferID":165,
	  "GolferFName":"Michael",
	  "GolferLName":"RadarReid",
	  "CurrentScoreRelPar":-8,
	  "EoMHandicap":0,
	  "CurrentNetScore":-8,
	  "img_name":"MikeReid.gif"
	}
	
     ]
}